apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hs4jwd054-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hs4jwd054-java-quarkus-gitops